
rabbitmq:
  namespace: rabbitmq
  clusterName: rabbitmq-ha-cluster
  username: hopr-gnosis-bridge
  password: "MyRabbitMQPassword"

amb:
  oracleValidator:
    address: "0x1234567890abcdef"
    privateKey: "SomeVerySecretPrivateKey"

xdai:
  oracleValidator:
    address: "0x1234567890abcdef"
    privateKey: "SomeVerySecretPrivateKey"

config:
  homeRpcUrl: "https://some.gnosis.rpc.url"
  foreignRpcUrl: "https://some.ethereum.rpc.url"
  foreignArchiveRpcUrl: "https://some.ethereum-archive.rpc.url"
  envVars:
    ORACLE_LOG_LEVEL: "debug"
    # latest block number in Gnosis Chain    
    ORACLE_HOME_START_BLOCK: "42974700"
    # latest block number in Ethereum
    ORACLE_FOREIGN_START_BLOCK: "23726268"