apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: {{ include "gnosis-bridge.fullname" . }}-redis
data:
  redis-additional.conf: |
    maxmemory 157810688
    maxmemory-policy allkeys-lru
    tcp-keepalive 400
    slowlog-max-len 158
    stream-node-max-bytes 2048
    # Empty line