apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: {{ include "gnosis-bridge.fullname" . }}
data:
  NODE_ENV: "production"
  ORACLE_BRIDGE_MODE: "ARBITRARY_MESSAGE"
  COMMON_HOME_BRIDGE_ADDRESS: "0x75Df5AF045d91108662D8080fD1FEFAd6aA0bb59"
  ORACLE_HOME_RPC_POLLING_INTERVAL: "5000"
  COMMON_FOREIGN_BRIDGE_ADDRESS: "0x4C36d2919e407f0Cc2Ee3c993ccF8ac26d9CE64e"
  ORACLE_FOREIGN_RPC_POLLING_INTERVAL: "5000"
  ORACLE_TX_REDUNDANCY: "true"
  COMMON_HOME_GAS_PRICE_SUPPLIER_URL: "eip1559-gas-estimation"
  COMMON_HOME_GAS_PRICE_SPEED_TYPE: "fast"
  COMMON_HOME_GAS_PRICE_FALLBACK: "1000000000"
  ORACLE_HOME_GAS_PRICE_UPDATE_INTERVAL: "600000"
  COMMON_HOME_GAS_PRICE_FACTOR: "1"
  COMMON_FOREIGN_GAS_PRICE_SUPPLIER_URL: "eip1559-gas-estimation"
  COMMON_FOREIGN_GAS_PRICE_SPEED_TYPE: "fast"
  COMMON_FOREIGN_GAS_PRICE_FALLBACK: "10000000000"
  ORACLE_FOREIGN_GAS_PRICE_UPDATE_INTERVAL: "600000"
  COMMON_FOREIGN_GAS_PRICE_FACTOR: "1"
  ORACLE_ALLOW_HTTP_FOR_RPC: "yes"
  ORACLE_REDIS_URL: {{ include "gnosis-bridge.fullname" . }}-redis:6379
  ORACLE_HOME_TX_RESEND_INTERVAL: "300000"
{{- with .Values.config.envVars }}
{{ toYaml . | indent 2 }}
{{ end }}
